[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "proc_comp"
version = "0.0.2-dev"
authors = [
    {name = "Tobias Frejo Rasmussen", email = "tfr@frejo.dk"},
]
requires-python = ">=3.10"
dependencies = []
